### ISSUE TITLE
General ToDos Issue

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/backend-template#65]
**General**
- [x] Font Awesome - install new version => https://github.com/joomla/joomla-cms/pull/24648
- [x] Tools icon for System settings  
- [x] Edit icon instead of cog for edit modules
- [x] Text-muted is visible: contrast-ratio and font-size
- [x]  rtl for cpanel icons and badges
- [ ] rtl for select fields in forms
- [x]  Focus on Dshboard Icons  in FF
- [x] Design Issue font-size of labels. 75% is too small as users say 
- [x] Focus is visible in main menu on navigations 
- [x] Header shadow is visible, not overlayed by the wrapper.
- [x] TinyMCE 5
- [ ] Hide columns
- [ ] Fix responsiveness
- [x] Fix Alerts/Warnings/Notifications
- [x] Sidebar menu in system dashboard is wrong (languages etc) => Should be fixed in normal tracker
- [x] Sidebar in com_config / Solve overwhelming number of items => Should be fixed in normal tracker
- Add breadcrumbs like in concept https://github.com/joomla/joomla-cms/issues/24500
- help & options not as a button but as icon see https://github.com/joomla/backend-template/issues/66
- [x] XML PR => Viviana PR: https://github.com/joomla/joomla-cms/pull/24284
- [x] SysInfo system manager icon missing from system settings
- [ ] Check scss / style code style possibilities @Jules Weigel @svom  

**Installation Screen**

Urgent
- [x]  Use the background image
- [x]  Finish Buttons: do we need icons together with externa-link-icons? => public tracker
- [x] Installer Quicker way of selecting the installation language => public tracker
- [x] Installer Responsiveness

Not Urgent
- [x] Header is responsive
- [x] Language Overview, label not readable, table fontsize needs adjustment, button needs to follow standard
- [x] Using https://github.com/joomla/joomla-cms/pull/23215 for Password field?
- [ ]  Check a1yy

Not in Scope
- (not template related***) Skip and Next in Installation is confusing and does two different things and screens. Please check the workflow and what needs to be done
- Installer Security check needs to be reimplemented https://github.com/joomla/joomla-cms/issues/18736 
- Installer over FTP
- InstallerRemove Sample Data install (add in template.sql concept)
- Installer Delete installation folder checkbox doesn't work

**Login Screen**
- [ ]  Fading effekt still "Jumps"
- [x]  Fix Bug issue #70 (user not authorised, sliding hides warning)
- [ ] Screen jumps if a user repeats wrong input
- [x] increase margin between Headline and Input fields (+1rem)
- [ ]  Chaning the vendor icon and colors testing and bugfixing
- [x]  https://github.com/joomla/backend-template/issues/27 Check if solved - if so please close Issue
- [ ]  Check if https://github.com/joomla/backend-template/issues/20 is solved
- [ ]  Complete Checklist https://github.com/joomla/backend-template/issues/7
- [x] Using https://github.com/joomla/joomla-cms/pull/23215 for Password field?
- [x] Eye Icon looks like using bold font type, can anyone check and fix? -> font-weight is normal

**Mobile Layout**

Urgent
- [ ]  Use the whole screen - there is too much padding for forms
- [x]  Fix #15 issue (make control group responsive)
- [x]  Create the mobile layout According to #41
- [x]  Provide detailed screens <-> Provide what needs to be on the screens
- [x]  Check if it solves this issue: https://github.com/joomla/backend-template/issues/31 
https://github.com/joomla/backend-template/issues/30
- [x]  Change Menu Toggle to (maybe) Burger Bar as the submenu items use the same icon and its confusing

**Navigation Issues**
- [x]   (not template related***) Test usage of Joomla and fix Usabilty issues like https://github.com/joomla/backend-template/issues/40

**Quick Icons**
https://github.com/joomla/backend-template/issues/38
- [x]  color styling
- [x] Check Browsers https://github.com/joomla/backend-template/issues/68
- [x] Paramters have text sho/hide instead of yes / no #116 - [ ]

**Color System and Backend Parameters**
- [x]  Create calculation System based on hue / and not (me)
- [x]  Add / Change parameters to Template
- [x] Add Hue Color slider
- [x] Parameter for Dark scheme
- [x] Parameter for monochrome scheme
- [x] Parameter to add fixed Saturation (-a11y ???)
- [ ] Nice to have: live Template update for color preview
- [x] Images have Parameter "alt-text" to images #111 

- [x]  https://github.com/joomla/backend-template/issues/25
- [x]  https://github.com/joomla/backend-template/issues/12
- [x]  https://github.com/joomla/backend-template/issues/1

**List Views**

Urgent
- [x]  External Link Icon not für published buttons in articles list
- [x] Fix Article Toolbar https://github.com/joomla/backend-template/issues/66 
- [x]  Links in the table are not recognizeable as links (for color-blinds) #9. (i.e. link to the author in articles)
- Options and Help are not Buttons just Icons at the top right, see the template concept

Not Urgent
- [x] Switcher: Set Color Danger to scss variable Danger (see view user-edit, switcher  "blocked")
- [ ] Fix Toolbar in other Views for Example Redirects according to issue #66
- [x] Proposal for Search Filter design https://github.com/joomla/backend-template/issues/67

Not in Scope
- [x] Check if Permission Table works - https://github.com/joomla/joomla-cms/issues/23628 (not template)
- [ ]  (not template related***) Ajax Options ? // https://github.com/joomla/backend-template/issues/37

**Save Buttons**
- [x]  Style according https://github.com/joomla/backend-template/issues/36
- [x]  Bring back the Save and New Option (went lost)

**Hide/Show Columns**
- [ ]  https://github.com/joomla/backend-template/issues/34

**Testing**
- [x]  Does this issue exist in our layout? If not - comment joomla/joomla-cms#23628

**Improving Filters**
- [x]  Creating Screens for Filter Options https://github.com/joomla/backend-template/issues/32, https://github.com/joomla/backend-template/issues/66
- [x]  develop it

**Alerts**
- [x]  (not template related***) Current state: Not accessible and not styled. Provide possible solutions to discuss

**Dashboards**

Urgent
- [x]  Add an own module is possible. 
- [x]  Extent System Settings Dashboard by Informations and with Icons in Headlines https://github.com/joomla/backend-template/issues/5
- [x]  Allow images for menu items
- [x]  Respect params for menu images

**Toolbar**
- [x]  No underline in frontend link
- [x]  Check if https://github.com/joomla/backend-template/issues/9 is still an issue
- [x] All buttons have focus
- [x]  removing Notification does not work @lavipr @fancyFranci 
- [x] Put Joomla Version in a red or green bubble like a notification or status. Put eventually alpha beta or RC below the Icon

**Article Edit Layout**
- [x]  https://github.com/joomla/backend-template/issues/6

**Action Buttons**
- [x]  https://github.com/joomla/backend-template/issues/3
