### ISSUE TITLE
Step #1 - Entry to the Backend: The new Login Design

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/backend-template#7]
Todos:
- [x] Eye-Icon to white background and blue font (button stays blue, text white)
- [x] Adjust size and positioning of the login box on desktop and mobile
- [x] Top margin in mobile view is correct
- [x] Limit login image in width and height
- [x] Form input error messages are below the form field
- [ ] IE 11 works
- [ ] Chrome works
- [ ] Firefox works (not yet, there is a jump in the fade)
- [ ] IE Edge works
- [ ] Safari works
- [ ] iOs works
- [ ] Android works
- [x] Display Site title in upper bar in mobile view
- [x] Check heading semantic
- [x] Clicking the eye button must not perform the login
- [x] Eye button maynot have an alt-attribuute
- [x] adjust the width of the left side to 4/12 columns of the whole width
- [x] Font Type is Roboto (generally for the Template)
- [x] Font site title Roboto, bold, 24px 
- [x] Font sitelink Roboto, regular, 14px 
- [x] Font Module Heading Roboto, bold, 18px 
- [x] Font Module content Roboto, regular, 14px 
- [x] Size Joomla Logo in Login window 45 x 45 px
- [x] Labels Roboto, bold, 11px color #20323F
- [x] Add Description  "For 2-Factor Authentification" right aligned  #1A466B
- [x] Eye and Login Button: Border Radius 2px, background #1A466B, color: #fff, box shadow color: 0,0,0,0.15  shadow settings: 0 0 4 0, Font Size 14px
- [x] Shadow Box Color 0,0,0,0.10,  shadow settings: 0 0 10 0 
- [x] Color credential link help #387EC3, underlined
- [x] Eye Button should have a margin towards the input box
- [x] Joomla Pattern color is currently wrong in the design, should be like in the draft
- [ ] Check Design consistance, are the font-sizes correct, does the fade work?
- [ ] Final checks after Color PR is done (EF) -> Is it possible to adjust colors and logos in the backend template stile, does any user action break the whole login?  https://github.com/joomla/backend-template/issues/12
- [x] Test with own module and looooong content
- [x] Are all labels readable / also regarding accessibility?
- [x] Is the form accessible?
- [x] check custom element from Dimitris and contact him about it
- [ ] check "input group" is not used for styling puposes
- [x] is the "eye" a real button (a11y) 
- [ ] Can we have a final check with bootlint? 
- [ ] Document the Login view in docs.joomla.org 
- [ ] Clean up SCSS files (move all bootstrap changes to the vendor folder)
- [x] Code review (https://github.com/joomla/backend-template/pull/44/files)
- [x] Images have the correct base-path to be loaded in the login-header and login-panel

 Updated Design:
![grafik](https://user-images.githubusercontent.com/828371/52273950-9aecb180-294b-11e9-800e-5a145fa23505.png)
 Small update on the Eye Button and the credentials link. Everything else is like in the designproposal.

![loginpage_mobile](https://user-images.githubusercontent.com/14434412/49723042-45a36500-fc66-11e8-82af-b4bc6fb79ca5.png)

(Old drafts)
First working package for the Joomla 4 backend:
Design of the login page:
![loginpage](https://user-images.githubusercontent.com/828371/49500926-13fb5a00-f872-11e8-8704-d046b218ae42.png)

Commented:
![loginpage_comments](https://user-images.githubusercontent.com/828371/49500939-19f13b00-f872-11e8-8267-d7f0f1d85eb0.png)

![loginpage](https://user-images.githubusercontent.com/828371/49500850-ea423300-f871-11e8-8481-8999210a4c20.png)

Description:
The new Login page integrates into the new backend design. It's not anymore a separate style and after login the elements should "flow" into the new template. Means at the login action the login  elements fade out and the left side fades to the menu color, a custom image would fade out. At loading the control panel in backend elements would fade in so that the login has an effect of a single side that builds up when login in.  Like required by marketing there is enough possibilty for the site creator to present himself and to customize the login to the client needs (Setup Logo, Colors, Image and Integrator Informations)

Requirements:
@svom - Can you do some rework on the mobile draft please?
@nadjak77 - Can you create a HTML and SCSS mockup on this and pass it to 
@fancyFranci and @lavipr to integrate webcomponents (alerts,...)
@Hackwar can you look at the PR from Dimitris and see if there is a sercure solution to the Password reveal as you mentioned?
@HLeithner can you check possibilities to make a 3Step Login like you mentioned?
@bembelimen can you help the team to create branches etc. ?
@chmst can you help @nadjak77 to create the structure and check the layout regarding a11y?

**Comment by bembelimen** [comment]
I would define the login as done.

Specific issues are created as stand alone issues.
